name: workflow-2
run-name: ${{ github.actor }} is learning GitHub Actions
# Controls when the workflow will run
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install 
      - run: npm test